# Generated by Django 5.1.6 on 2025-02-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cooking_time', models.IntegerField()),
                ('ingredients', models.TextField()),
                ('directions', models.TextField()),
                ('nutrition', models.JSONField()),
                ('image_url', models.URLField()),
                ('recipe_type', models.CharField(max_length=100)),
            ],
        ),
    ]
